# web server
PORT=8806
BODY_LIMIT="1M"
JWT_EXPIRE_TIME=1440

#database
SHARD_NUMBER = 1
SHARD_ADDRESS=["127.0.0.1:3307"]
SHARD_TYPE = ["mysql"]
SHARD_NAME = ["stock"]
SHARD_USER = ["root"]
SHARD_PASSWORD = ["123"]
DB_ARGS="charset=utf8&collation=utf8_general_ci&parseTime=true&loc=Asia%2FHo_Chi_Minh"
DB_MAX_IDLE=2
DB_MAX_OPEN=4

#stock list
STOCK_LIST = ["GOOG", "FSLY", "TBIO", "INO", "AAPL", "CBL", "PLUG", "MSFT", "BRN", "LK", "FFHL", "LLEX", "SPR", "WKHS", "SNY", "KIRK", "SONO", "SNSS", "FRSX", "PTN", "DLOC", "NNDM", "PENN", "HEPA", "BOX", "SNYNF", "MARA", "STIM", "APYX", "CRSP", "CJJD"]

#startdate enddate
START_DATE = "2015-01-01"
END_DATE = "2021-05-25"
